    // constants/errorCodes.js

export const ERROR_CODES = Object.freeze({
  VALIDATION: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  NOT_FOUND: "NOT_FOUND",
  DUPLICATE: "DUPLICATE",
  GMAIL_AUTH: "GMAIL_AUTH_FAILED",
  INTERNAL: "INTERNAL_ERROR",
});
